Add support for HTML comments
a-h/templ pull request #161
Opened 2023-09-19 19:11 UTC by tantalic

This adds the ability to use HTML style comments, wrapped in` `. HTML comments are parsed into a new node type and included in the template output.

Basic design/approach followed #79. This is my first attempt to work on the templ project. I tried to follow the style/practices I see elsewhere. Happy to take any feedback/changes into this PR to move it along in the right direction for the project.

2023-09-19 23:01 UTC, a-h requested changes
Thanks for getting involved!

This looks like a great start, but some tests around it are important. They help to make sure that we don't break expected behaviour between releases.

There are two major types of test in templ. One tests that the parser behaves as expected - i.e. produces errors when it should, and handles edge cases. You can see an example of that in https://github.com/a-h/templ/blob/main/parser/v2/doctypeparser_test.go

The other is to test that the appropriate HTML output is generated - a more complete integration test.

In temp, do we expect the comments to be included, or should they be elided from the HTML output?

Either way, a test would show the expected behaviour and make sure we don't break it during refactoring or bug fixes. Here's an example of the generation style test - https://github.com/a-h/templ/tree/main/generator/test-templ-element

2023-09-20 04:37 UTC, tantalic commented on parser/v2/comment.go
> +	end   parse.Parser[string]
My thought here was that this struct could be extended to support `//` style comments as well. However, I’m not entirely sure yet if that is feasible or not yet, so curious on your thoughts there.

2023-09-20 07:11 UTC, joerdav commented on parser/v2/comment.go
> +	end   parse.Parser[string]
Personally I think that the implementation for Go style comments will be quite different, they won't arrive in the resulting HTML, but probably should end up in the generated Go code to support godoc style comments and build tag style comments.

2023-09-20 18:09 UTC, tantalic commented on parser/v2/templateparser.go
> +			fmt.Println(commentNode.Contents)
I would have sworn I did a search for println calls specifically to avoid doing this. 🤦

2023-09-20 18:21 UTC, tantalic commented
@a-h & @joerdav - Thank you for great feedback on this PR. I've addressed all the changes except for the tests which I will make some time to work on.

2023-09-21 00:31 UTC, a-h commented on parser/v2/templateparser.go
> +			fmt.Println(commentNode.Contents)
We've all done it!

2023-09-28 15:28 UTC, tantalic commented
@a-h - I think this is ready for review again.

2023-09-28 20:38 UTC, a-h commented
Thanks! Will take a look tomorrow. 🙌

2023-09-29 07:40 UTC, a-h approved these changes

2023-09-29 07:40 UTC, merged

2023-09-29 07:41 UTC, a-h commented
Thanks a lot, that's great!