feat: WIP attemt org imports when formatting with a file name
a-h/templ pull request #793
Opened 2024-06-14 11:05 UTC by joerdav

2024-06-18 06:44 UTC, a-h commented
Looking good! I'll give it a proper review when I can. Thanks so much for this, it's such a cool feature.

2024-06-18 07:17 UTC, joerdav commented
No problem! Let me know if you have questions about the code, or any changes for me to make.

2024-06-22 10:35 UTC, a-h requested changes
Just a minor naming thing, I'll pick it up. Thanks!

2024-06-22 10:43 UTC, a-h approved these changes

2024-06-22 10:44 UTC, merged